input('Press Enter to start the Quiz Game...')
name = input('What is your name? ')
input(f'Hello {name}! Get ready for the quiz. (Press Enter to continue...)')
print('Welcome to the Quiz Game!')
print('You will be asked 15 questions. Try to answer them correctly!')
print('You have only 1 chance to win the game. Good luck!\n')
print('the score for the 1st question is 100')
print('the first question is:What is the hardest natural substance on Earth?')
print('A: Diamond')
print('B: Iron')
print('C:Quartz')
print('D:Graphite')
answer1 = input('Your answer is:')
if answer1 == 'A' or answer1 == 'a':
    print('Correct! You earned 100 points. \n')
else:
    print('Wrong answer. The correct answer is A: Diamond. Game Over!')
    print('Better luck next time!')
    print(f'Your total score is 0 points.')
    breakpoint
print('the score for the 2nd question is 200')
print('Which scientist proposed the three laws of motion?')
print('A: Albert Einstein')
print('B: Isaac Newton')
print('C: Galileo Galilei')
print('D: Johannes Kepler')
answer2 = input('Your answer is:')
if answer2 == 'B' or answer2 == 'b':
    print('Correct! You earned 200 points. \n')
    print('You are doing very great choices')
else:
    print('Wrong answer. The correct answer is B: Isaac Newton. Game Over!')
    print('Better luck next time!')
    print(f'Your total score is 100 points.')
    exit()
print('the score for the 3rd question is 300')
print('What is the only metal that is liquid at room temperature?')
print('A: Mercury')
print('B: Lead')
print('C: Silver')
print('D: Gold')
answer3 = input('Your answer is:')
if answer3 == 'A' or answer3 == 'a':
    print('Correct! You earned 300 points. \n')
    print('You are doing very great choices')
else:
    print('Wrong answer. The correct answer is A: Mercury. Game Over!')
    print('Better luck next time!')
    print(f'Your total score is 300 points.')
    exit()
print('the score for the 4th question is 400')
print('Which planet has the fastest rotation in our solar system?')
print('A: Jupiter')
print('B: Saturn')
print('C: Earth')
print('D: Mars')
answer4 = input('The answer is: ')
if answer4 == 'A' or answer4 == 'a':
    print('Great! It is getting interesting')
    print('So move into next question')
else:
    print('FAAAAAAAAIL')
    print('It was amazing but not enough smart')
    print('The end  ')
print('Score for the 5th question is 500')
print('So, here is the question')
print('Who was the first person to propose that the Earth revolves around the Sun?')
print('A: Galilleo Gallilei')
print('B: Nicolaus Copernicus')   
print('C: Johannes Kepler')
print('D: Aristotle')
answer5 = input('The answer is: ')
if answer5 == 'B' or answer5 == 'b':
    print('Correct! Let me be faster')
else:
    print('Wrong you lost')
print('The score for the 6th question is 600')
print('In computer science, what does “HTTP” stand for?')
print('A: HyperText Transfer Protocol')
print('B: Hyperlink Text Transfer Process')
print('C: High Transfer Text Protocol')
print('D: Hyper Transfer Type Program')
answer6 = input('Your answer is:')
if answer6 == 'A' or answer6 == 'a':
    print('Correct! You earned 1500 points. \n')
else:
    print('Wrong answer. The correct answer is A: HyperText Transfer Protocol ')
    print('Better luck next time!')
    print(f'Your total score is  points.')
    exit()
print('the score for the 7th question is 700')
print('Which ancient wonder was located in the city of Babylon?')
print('A: The Great Pyramid')
print('B: Hanging Gardens')
print('C: Temple of Artemis')
print('D: Statue of Zeus')
answer7 = input('Your answer is:')
if answer7 == 'B' or answer7 == 'b':
    print('Correct! You earned 2800 points. \n')
    print('You are doing very great choices')
else:
    print('Wrong answer. The correct answer is B: Isaac Newton. Game Over!')
    print('Better luck next time!')
    print(f'Your total score is 2100 points.')
    exit()
print('the score for the 8th question is 800')
print('What is the powerhouse of the cell?')
print('A:Nucleus')
print('B: Ribosome')
print('C: Mitochondria')
print('D: Cytoplasm')
answer8 = input('Your answer is:')
if answer8 == 'c' or answer8 == 'C':
    print('Correct! You earned 800 points. \n')
    print('You are doing very great choices')
else:
    print('Wrong answer. The correct answer is A: Mercury. Game Over!')
    print('Better luck next time!')
    print(f'Your total score is 3600 points.')
    exit()
print('the score for the 9th question is 900')
print('Who wrote the philosophical book The Republic?')
print('A: Socrates')
print('B: Aristotle')
print('C: Plato')
print('D: Marcus Aurelius')
answer9 = input('The answer is: ')
if answer9 == 'C' or answer9 == 'c':
    print('Great! It is getting interesting')
    print('So move into next question')
else:
    print('FAAAAAAAAIL')
    print('It was amazing but not enough smart')
    print('The end  ')
print('Score for the 10th question is 1000')
print('So, here is the question')
print('What is the most abundant gas in Earth’s atmosphere?')
print('A: Oxygen')
print('B: Nitrogen')   
print('C: Carbon Dioxide')
print('D: Argon')
answer10 = input('The answer is: ')
if answer10 == 'B' or answer10 == 'b':
    print('100% Right')
else:
    print('Wrong you lost')
    print('The end')
print('the score for the 11th question is 1100')
print('Which scientist discovered penicillin?')
print('A: Alexander Flemingd')
print('B: Louis Pasteur')
print('C: Marie Curie')
print('D: Gregor Mendel')
answer11 = input('Your answer is:')
if answer11 == 'A' or answer11 == 'a':
    print('Correct! You earned 1100 points. \n')
else:
    print('Wrong answer. The correct answer is A: Diamond. Game Over!')
    print('Better luck next time!')
    breakpoint
print('the score for the 12th question is 1200')
print('What is the smallest prime number greater than 100?')
print('A: 101')
print('B: 103')
print('C: 109')
print('D: 1808')
answer12 = input('Your answer is:')
if answer12 == 'A' or answer12 == 'a':
    print('You are doing very great choices')
else:
    print('Wrong answer. The correct answer is A: 101')
    print('Better luck next time!')
    breakpoint
print('the score for the 13rd question is 1300')
print('What is the rarest naturally occurring element on Earth?')
print('A: Astatine')
print('B: Francium')
print('C: Californium')
print('D: Technetium')
answer13 = input('Your answer is:')
if answer13 == 'A' or answer13 == 'a':
    print('Correct! You earned 1300 points. \n')
    print('Ok move into the next question')
else:
    print('Wrong answer. The correct answer is A: Mercury. Game Over!')
    print('Better luck next time!')
    breakpoint
print('the score for the 4th question is 400')
print('Which language has the most native speakers in the world?')
print('A: English')
print('B: Hindi')
print('C: Mandarin Chinese')
print('D: Spanish')
answer14 = input('The answer is: ')
if answer14 == 'B' or answer14 == 'b':
    print('Great! It is getting interesting')
    print('So move into next question')
else:
    print('Unfortunately you lost the game. ')
    print('The end  ')
print('Score for the 15th question is 1500')
print('So, here is the question')
print('What mathematical constant is known as Euler’s Number?')
print('A: π')
print('B: e')   
print('C: φ')
print('D: i')
answer15 = input('The answer is: ')
if answer15 == 'B' or answer15 == 'b':
    print('Correct! Let me be faster')
else:
    print('Wrong you lost')
    print('You choose a wrong answer in the end')
    print('It was vey interesting to play a quiz game with you')
    print('Better luck next time')
print('It was vey interesting to play a quiz game with you')
print('You earned a 12.000 credits in total.')
print('YOU SET THE 1ST RECORD AMONG THE CONTESTANTS')
print('You are very smart')
print('Come back again in next games')
print('See you soon')